# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/webserver_fw/webserver_fw.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==webserver_fw || ORIG_REF_NAME==webserver_fw} -quiet] -quiet

# IP: bd/webserver_fw/ip/webserver_fw_processing_system7_0_0/webserver_fw_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==webserver_fw_processing_system7_0_0 || ORIG_REF_NAME==webserver_fw_processing_system7_0_0} -quiet] -quiet

# XDC: /home/overlord/ece520/assignments/lab11/hardware/webserver_firmware/webserver_firmware.gen/sources_1/bd/webserver_fw/webserver_fw_ooc.xdc
